name: Deploy prod Shopify app config

on:
  push:
    branches:
      - main

jobs:
  shopify-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - name: shopify app deploy
        env:
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
        run: npx shopify app deploy --config ai-chat-app --allow-updates
